### ISSUE TITLE
interested in a CHIP-SEQ Track file from one of the VSN case studies

### ISSUE THREAD

**Issue by deevdevil88** [vib-singlecell-nf/vsn-pipelines-examples#3]
Hi, 
I am interested in a CHIPseq track file used in one of your case studies, Davie 2018 paper. As currently, there are no CHIP-Seq tracks for fly on your cisTarget database, i was wondering if you have the CHIP-SEQ track file used in this example available anywhere for other users to use?

Best,
Devika

**Comment by dweemx** [comment]
Hi @deevdevil88,

Links have just been added for the tracks here: https://resources.aertslab.org/cistarget/

![image](https://user-images.githubusercontent.com/16015936/106789219-44a5cc80-6652-11eb-9930-835c1aaf7b0c.png)

![image](https://user-images.githubusercontent.com/16015936/106789156-2d66df00-6652-11eb-9889-966ef3e2aced.png)

**Comment by deevdevil88** [comment]
hi @dweemx  
Thats Awesome :D. Thank you for updating the cistarget database straightaway. I can now use these to run my analyses.

Devika
